export const LOAD_STUDENT_ANNOUNCEMENT_DATA = 'LOAD_STUDENT_ANNOUNCEMENT_DATA';
export const LOAD_STUDENT_COMPANY_POSTS_DATA = 'LOAD_STUDENT_COMPANY_POSTS_DATA';

export const LOAD_ADMIN_ANNOUNCEMENT_DATA = 'ADMIN/LOAD_ANNOUNCEMENT_DATA';
export const LOAD_ADMIN_COMPANY_DATA = 'ADMIN/LOAD_COMPANY_DATA';
export const LOAD_ADMIN_USER_DATA = 'ADMIN/LOAD_USER_DATA';
export const LOAD_ADMIN_REQUEST_DATA = 'ADMIN/LOAD_REQUEST_DATA';
export const LOAD_ADMIN_POST_DATA = 'ADMIN/LOAD_POST_DATA';