export const LOAD_STUDENT_ANNOUNCEMENT_DATA = 'LOAD_STUDENT_ANNOUNCEMENT_DATA';
export const LOAD_STUDENT_COMPANY_POSTS_DATA = 'LOAD_STUDENT_COMPANY_POSTS_DATA';

export const LOAD_ADMIN_ANNOUNCEMENT_DATA = 'LOAD_ADMIN_ANNOUNCEMENT_DATA';
export const LOAD_ADMIN_COMPANY_POSTS_DATA = 'LOAD_ADMIN_COMPANY_POSTS_DATA';